In [61]:
# Import the libraries

%pip install yfinance 
%pip install plotly

import yfinance as yf

import pandas as pd 
import numpy as np 

import plotly.graph_objects as go 
import plotly.express as px 
#import plotly.io as pio

Requirement already satisfied: yfinance in /usr/local/python/3.12.1/lib/python3.12/site-packages (1.2.1)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (3.0.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (2.4.4)
Requirement already satisfied: requests>=2.31 in /home/codespace/.local/lib/python3.12/site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (2026.1.post1)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (4.0.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/codespace/.local/lib/python3.12/site-packages (from yfinance) (4.14.2)
Requirement already satisfied: curl_cffi>=0.15 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (7.34.1)
Requirement already satisfied: websockets>=13.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from yfinance) (16.0)
Requirement already satisfied: soupsieve>1.2 in /home/codespace/.local/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /home/codespace/.local/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (2025.11.12)
Requirement already satisfied: rich in /usr/local/python/3.12.1/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: pycparser in /home/codespace/.local/lib/python3.12/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from rich->curl_cffi>=0.15->yfinance) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/codespace/.local/lib/python3.12/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: plotly in /usr/local/python/3.12.1/lib/python3.12/site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from plotly) (2.19.0)
Requirement already satisfied: packaging in /home/codespace/.local/lib/python3.12/site-packages (from plotly) (25.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [69]:
# Download the stock data from yfinance
import yfinance as yf
# Define the stock ticker and the date range
tickers = ['AAPL']
start_date = '2020-01-01'
end_date = '2026-01-01'

# Download the stock data
stocks = yf.download(tickers, start=start_date, end=end_date, auto_adjust=True)

# Arrange the data so that 'Close' price can directly be used for plotting and calculations
stocks.columns = stocks.columns.droplevel(1)  # Drop the ticker level from columns

# reset the index to make 'Date' a column
stocks.reset_index(inplace=True)

stocks.head()

[*********************100%***********************]  1 of 1 completed

Price       Date      Close       High        Low       Open     Volume
0     2020-01-02  72.400528  72.460791  71.156689  71.409793  135480400
1     2020-01-03  71.696640  72.455958  71.472462  71.629145  146322800
2     2020-01-06  72.267921  72.306491  70.568495  70.819193  118387200
3     2020-01-07  71.928070  72.533110  71.708710  72.277594  108872000
4     2020-01-08  73.085114  73.386431  71.631559  71.631559  132079200

In [72]:
### Add Bollinger Bands to the stock data
# Calculate the 20-day moving average and standard deviation

stocks['MA20'] = stocks['Close'].rolling(window=20).mean()
stocks['STD20'] = stocks['Close'].rolling(window=20).std()

# Calculate the upper and lower Bollinger Bands
stocks['UpperBand'] = stocks['MA20'] + (stocks['STD20'] * 2)
stocks['LowerBand'] = stocks['MA20'] - (stocks['STD20'] * 2)    
stocks.dropna(inplace=True)
#.reset_index(inplace=True)  # Drop rows with NaN values resulting from rolling calculations

stocks.head(25)

# Plot the stock price and Bollinger Bands
#pio.renderers.default = "browser"

fig = go.Figure()
fig.add_trace(go.Scatter(x=stocks.index, y=stocks['Close'], mode='lines', name='Close Price'))

fig.add_trace(go.Scatter(x=stocks.index, 
                         y=stocks['UpperBand'], 
                         mode = 'lines', 
                         name='Upper Bollinger Band', 
                         line=dict(color='red', dash='dash')))

fig.add_trace(go.Scatter(x=stocks.index, 
                         y=stocks['LowerBand'], 
                         mode = 'lines', 
                         name='Lower Bollinger Band', 
                         line=dict(color='red', dash='dash')))
fig.show()

In [ ]:
stocks.head(25)

Price,Date,Close,High,Low,Open,Volume,MA20,STD20,UpperBand,LowerBand
Ticker,,AAPL,AAPL,AAPL,AAPL,AAPL,,,,
19,2020-01-30,78.070107,78.123139,76.835912,77.267400,126743200,75.217593,2.016557,79.250707,71.184480
20,2020-01-31,74.608582,77.783257,74.314496,77.361412,199588400,75.327996,1.911940,79.151876,71.504116
21,2020-02-03,74.403679,75.567966,72.851292,73.352680,173788400,75.463348,1.728340,78.920027,72.006669
22,2020-02-04,76.860016,77.050450,75.601715,76.006683,136616400,75.692953,1.580166,78.853284,72.532621
23,2020-02-05,77.486755,78.284643,76.884121,77.985731,118826800,75.970887,1.356078,78.683043,73.258731
24,2020-02-06,78.393127,78.395540,77.199915,77.756749,105425600,76.236288,1.278791,78.793869,73.678706
25,2020-02-07,77.327522,78.141800,76.837022,77.892926,117684000,76.370789,1.242739,78.856268,73.885310
26,2020-02-10,77.694817,77.694817,75.834301,75.914035,109348800,76.515218,1.218965,78.953149,74.077288
27,2020-02-11,77.226036,78.262613,77.008574,78.190128,94323200,76.556300,1.228839,79.013979,74.098621
28,2020-02-12,79.059982,79.064812,77.675464,77.675464,113730400,76.740663,1.315468,79.371598,74.109728
29,2020-02-13,78.497017,78.823213,78.129748,78.332713,94747600,76.913029,1.308069,79.529168,74.296890
30,2020-02-14,78.516350,78.765224,78.008934,78.465603,80113600,77.039356,1.335921,79.711197,74.367515
31,2020-02-18,77.078659,77.259878,76.017918,76.199137,152531200,77.051735,1.335036,79.721806,74.381663
32,2020-02-19,78.194984,78.424532,77.320300,77.320300,93984000,77.145963,1.346418,79.838799,74.453128
33,2020-02-20,77.392784,78.443858,76.887787,77.955777,100566000,77.186463,1.340756,79.867976,74.504950
34,2020-02-21,75.640999,77.429037,75.024856,76.986857,129554000,77.120932,1.384165,79.889262,74.352602
35,2020-02-24,72.048004,73.497759,69.885457,71.825712,222195200,76.886840,1.790149,80.467137,73.306542
36,2020-02-25,69.607597,73.099095,69.136431,72.717329,230673600,76.643540,2.371627,81.386795,71.900286
37,2020-02-26,70.711815,71.975521,69.225817,69.233066,198054800,76.350111,2.717653,81.785416,70.914806
38,2020-02-27,66.089516,69.105010,65.954206,67.921044,320605600,75.745417,3.516374,82.778166,68.712669
39,2020-02-28,66.050865,67.271081,61.945643,62.160693,426510000,75.144455,4.080054,83.304563,66.984348
40,2020-03-02,72.200241,72.835718,67.104351,68.206165,341397200,75.024038,4.131911,83.287861,66.760215
41,2020-03-03,69.907204,73.454270,69.056676,73.374537,319475600,74.799215,4.286867,83.372949,66.225480
42,2020-03-04,73.149818,73.309292,70.827797,71.627578,219178400,74.613705,4.273250,83.160206,66.067204
43,2020-03-05,70.777077,72.379051,70.412219,71.405298,187572800,74.278221,4.299125,82.876471,65.679971